name: Quiz Games Master
description: The master of all quizzes
android: https://play.google.com/store/apps/details?id=com.quizgamesmaster.squidquizgame
iOS: https://apps.apple.com/us/app/squiz-quiz-for-squid-fans/id1589587076
